name: Annonce Discord Novaly-Store

on:
  release:
    types: [published]

jobs:
  envoyer-sur-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send embed message with logo to Discord
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          COMMENTAIRE="${{ github.event.release.name }}"
          
          # Remplace l'URL ci-dessous par le lien direct de ton logo (lien Raw GitHub ou autre)
          LOGO_URL="https://firebasestorage.googleapis.com/v0/b/novaly-a80f7.firebasestorage.app/o/logo1.png?alt=media&token=217eb083-ea50-4c6e-806a-5c6e6b5d429a"

          # Construction du message en JSON (Embed Discord)
          payload=$(cat <<EOF
          {
            "embeds": [
              {
                "title": "🚀 Novaly $VERSION is available !",
                "description": "**$COMMENTAIRE**\n\n👉 [Joue dès maintenant sur le site](https://novaly-store.fr)",
                "color": 16711680,
                "thumbnail": {
                  "url": "$LOGO_URL"
                }
              }
            ]
          }
          EOF
          )

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$payload" \
          ${{ secrets.DISCORD_WEBHOOK }}